# HR Analytics : Workforce Insights & Employee Trends

 ## Business Problem

The HR department lacks a centralized system to monitor key workforce metrics such as employee headcount, gender diversity, salary distribution, department-wise employee strength, and employee attrition. As a result, decision-making related to workforce planning, budgeting, and employee management becomes time-consuming and less effective.

## Project Objective

The objective of this project is to develop an interactive HR Analytics Dashboard that provides actionable insights into workforce data. The dashboard helps HR managers and business leaders:

 * Monitor total headcount, active employees, and terminated employees.

* Analyze employee distribution across departments and locations.

* Track gender diversity within the organization.

* Evaluate salary distribution by department and employee groups.

* Identify workforce trends to support strategic HR decision-making.

* Improve reporting efficiency through interactive visualizations and real-time insights.

### Tools Used: 
* SQL Server
* Python 
* Power BI 
* Excel.

In [2]:
# import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [218]:
## Importing the file 

HR_Df = pd.read_csv("C:/Users/charp/OneDrive/Desktop/Data Analytics projects/HR Dashboard Project/HR Dashboard/HRData.csv")

HR_Df.head(5)

,EmployeeID,EmployeeName,Salary,Position,State,DateOfBirth,Gender,MaritalStatus,HiringDate,TerminationDate,EmploymentStatus,Department,RecruitmentSource,PerformanceScore,EngagementSurvey,EmployeeSatisfaction
0,1,John Smith,62506,Production Technician I,MA,07/10/83,M,Single,7/5/2011,NaN,Active,Production,LinkedIn,Exceeds,4.60,5
1,2,Sarah Johnson,104437,Sr. DBA,MA,05/05/75,M,Married,3/30/2015,6/16/2016,Voluntarily Terminated,IT/IS,Indeed,Fully Meets,4.96,3
2,3,Michael Williams,64955,Production Technician II,MA,09/19/88,F,Married,7/5/2011,9/24/2012,Voluntarily Terminated,Production,LinkedIn,Fully Meets,3.02,3
3,4,Emily Brown,64991,Production Technician I,MA,09/27/88,F,Married,1/7/2008,NaN,Active,Production,Indeed,Fully Meets,4.84,5
4,5,David Jones,50825,Production Technician I,MA,09/08/89,F,Divorced,7/11/2011,9/6/2016,Voluntarily Terminated,Production,Google Search,Fully Meets,5.00,4

In [125]:
HR_Df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   EmployeeID            311 non-null    int64
 1   EmployeeName          311 non-null    object
 2   Salary                311 non-null    int64
 3   Position              311 non-null    object
 4   State                 311 non-null    object
 5   DateOfBirth           311 non-null    object
 6   Gender                311 non-null    object
 7   MaritalStatus         311 non-null    object
 8   HiringDate            311 non-null    object
 9   TerminationDate       104 non-null    object
 10  EmploymentStatus      311 non-null    object
 11  Department            311 non-null    object
 12  RecruitmentSource     311 non-null    object
 13  PerformanceScore      311 non-null    object
 14  EngagementSurvey      311 non-null    float64
 15  EmployeeSatisfaction  311 non-null    int64
dtypes: float64(1), int64(3), object(12)
memory usage: 39.0+ KB

In [5]:
print(HR_Df.describe())

       EmployeeID         Salary  EngagementSurvey  EmployeeSatisfaction
count  311.000000     311.000000        311.000000            311.000000
mean   156.000000   69020.684887          4.110000              3.890675
std     89.922189   25156.636930          0.789938              0.909241
min      1.000000   45046.000000          1.120000              1.000000
25%     78.500000   55501.500000          3.690000              3.000000
50%    156.000000   62810.000000          4.280000              4.000000
75%    233.500000   72036.000000          4.700000              5.000000
max    311.000000  250000.000000          5.000000              5.000000

In [6]:
HR_Df.isnull().sum()

EmployeeID                0
EmployeeName              0
Salary                    0
Position                  0
State                     0
DateOfBirth               0
Gender                    0
MaritalStatus             0
HiringDate                0
TerminationDate         207
EmploymentStatus          0
Department                0
RecruitmentSource         0
PerformanceScore          0
EngagementSurvey          0
EmployeeSatisfaction      0
dtype: int64

In [7]:
HR_Df['TerminationDate']

0            NaN
1      6/16/2016
2      9/24/2012
3            NaN
4       9/6/2016
         ...
306          NaN
307    9/29/2015
308          NaN
309          NaN
310          NaN
Name: TerminationDate, Length: 311, dtype: object

In [8]:
HR_Df['TerminationDate'] = HR_Df['TerminationDate'].fillna(HR_Df['TerminationDate'].mode()[0])

In [9]:
HR_Df['TerminationDate'].isnull().sum()

np.int64(0)

In [10]:
HR_Df['TerminationDate']

0      11/4/2015
1      6/16/2016
2      9/24/2012
3      11/4/2015
4       9/6/2016
         ...
306    11/4/2015
307    9/29/2015
308    11/4/2015
309    11/4/2015
310    11/4/2015
Name: TerminationDate, Length: 311, dtype: object

In [11]:
HR_Df.isnull().sum()

EmployeeID              0
EmployeeName            0
Salary                  0
Position                0
State                   0
DateOfBirth             0
Gender                  0
MaritalStatus           0
HiringDate              0
TerminationDate         0
EmploymentStatus        0
Department              0
RecruitmentSource       0
PerformanceScore        0
EngagementSurvey        0
EmployeeSatisfaction    0
dtype: int64

## KPI Analysis

### Head Count year wise

In [220]:
print(type(HR_Df['HiringDate']))

<class 'pandas.core.series.Series'>

In [221]:
print(HR_Df['HiringDate'].dtype)

object

In [222]:
HR_Df['year'] = pd.to_datetime(HR_Df['HiringDate'], errors = 'coerce')

print(HR_Df['year'].dtype)

datetime64[ns]

In [223]:
Head_Count = HR_Df.groupby(HR_Df['year'].dt.year).size().reset_index(name = 'Head_Count')

print(Head_Count)

    year  Head_Count
0   2006           1
1   2007           2
2   2008           3
3   2009           7
4   2010           9
5   2011          83
6   2012          45
7   2013          44
8   2014          60
9   2015          36
10  2016          14
11  2017           6
12  2018           1

#### Active Employee Count

In [224]:
Active_EMP = HR_Df[HR_Df['EmploymentStatus'] == 'Active']

Active_EMP_COunt = Active_EMP.groupby(Active_EMP['year'].dt.year).size().reset_index(name = 'Active_Count')

# Rename Column 
Active_EMP_COunt.columns = ['year', 'Active_Count']

Active_EMP_COunt

    year  Active_Count
0   2006             1
1   2007             1
2   2008             2
3   2009             4
4   2010             6
5   2011            24
6   2012            29
7   2013            37
8   2014            53
9   2015            29
10  2016            14
11  2017             6
12  2018             1

### Active EMP %

In [225]:
# Merging both dataframes 
Active_Percentage = pd.merge(Head_Count, Active_EMP_COunt, on='year')

# Calculating the Percentage 
Active_Percentage['Active_EMP_%'] = (Active_Percentage['Active_Count'] / Active_Percentage['Head_Count'] * 100).round(2)

Active_Percentage[['year','Active_EMP_%']]

    year  Active_EMP_%
0   2006        100.00
1   2007         50.00
2   2008         66.67
3   2009         57.14
4   2010         66.67
5   2011         28.92
6   2012         64.44
7   2013         84.09
8   2014         88.33
9   2015         80.56
10  2016        100.00
11  2017        100.00
12  2018        100.00

### Terminated Employee_count

In [226]:
# Replacing the values
HR_Df['EmploymentStatus'] = HR_Df['EmploymentStatus'].replace({'Voluntarily Terminated':'Terminated','Terminated for Cause':'Terminated'})

Terminated_EMP = HR_Df[HR_Df['EmploymentStatus'] == "Terminated"]

Terminate_EMP_Count  = Terminated_EMP.groupby(Terminated_EMP['year'].dt.year).size().reset_index(name = 'terminated_count')

#rename column
Terminate_EMP_Count.columns = ['year', 'terminated_count']

Terminate_EMP_Count

   year  terminated_count
0  2007                 1
1  2008                 1
2  2009                 3
3  2010                 3
4  2011                59
5  2012                16
6  2013                 7
7  2014                 7
8  2015                 7

### Terminated Employee %

In [227]:
Terminated_Percentage = pd.merge(Head_Count,Terminate_EMP_Count, on= 'year')

# Calculating EMP % 
Terminated_Percentage['Terminated_emp_%'] = (Terminated_Perentage['terminated_count'] / Terminated_Perentage['Head_Count'] * 100).round(2)

Terminated_Percentage[['year', 'Terminated_emp_%']]

   year  Terminated_emp_%
0  2007             50.00
1  2008             33.33
2  2009             42.86
3  2010             33.33
4  2011             71.08
5  2012             35.56
6  2013             15.91
7  2014             11.67
8  2015             19.44

### Male Count

In [228]:
# Checking the value 
print(HR_Df['Gender'].unique())

['M ' 'F']

In [229]:
# M Contain Extra Space so removing it
HR_Df['Gender']= HR_Df['Gender'].str.strip()

In [230]:
Male_Count = HR_Df[HR_Df['Gender'] =='M']

Male_Count = Male_Count.groupby(Male_Count['year'].dt.year).size().reset_index(name = 'Male_Count')

# Rename column name
Male_Count.columns = ['year','Male_Count']

Male_Count

    year  Male_Count
0   2006           1
1   2007           2
2   2009           2
3   2010           4
4   2011          31
5   2012          22
6   2013          17
7   2014          29
8   2015          15
9   2016           6
10  2017           5
11  2018           1

### Male Count %

In [231]:
Male_percent = pd.merge(Head_Count, Male_Count, on = 'year')

# CalCulating Male Emp % 
Male_percent['Male_emp_%'] = (Male_percent['Male_Count'] / Male_percent['Head_Count'] *100).round(2)

#Renaming the Columns

Male_percent[['year','Male_emp_%']]

    year  Male_emp_%
0   2006      100.00
1   2007      100.00
2   2009       28.57
3   2010       44.44
4   2011       37.35
5   2012       48.89
6   2013       38.64
7   2014       48.33
8   2015       41.67
9   2016       42.86
10  2017       83.33
11  2018      100.00

## Female Emp Count

In [232]:
Female_Count = HR_Df[HR_Df['Gender'] == 'F']

Female_Count = Female_Count.groupby(Female_Count['year'].dt.year).size().reset_index(name = 'Female_Count')

# Renaming the column 
Female_Count.columns = ['year','Female_Count']

Female_Count

   year  Female_Count
0  2008             3
1  2009             5
2  2010             5
3  2011            52
4  2012            23
5  2013            27
6  2014            31
7  2015            21
8  2016             8
9  2017             1

### Female Emp %

In [233]:
Female_Percent = pd.merge(Head_Count,Female_Count, on = 'year')

Female_Percent['Female_Emp_%'] = (Female_Percent['Female_Count'] / Female_Percent['Head_Count'] * 100).round(2)

Female_Percent[['year','Female_Emp_%']]

   year  Female_Emp_%
0  2008        100.00
1  2009         71.43
2  2010         55.56
3  2011         62.65
4  2012         51.11
5  2013         61.36
6  2014         51.67
7  2015         58.33
8  2016         57.14
9  2017         16.67

###  Year wise Total Salary

In [234]:
Year_wise_Salary = HR_Df.groupby(HR_Df['year'].dt.year)['Salary'].sum().reset_index(name = "Total_Salary")

Year_wise_Salary

    year  Total_Salary
0   2006         64397
1   2007        114177
2   2008        176504
3   2009        552430
4   2010        737753
5   2011       5238328
6   2012       3118323
7   2013       2877640
8   2014       4155746
9   2015       2702956
10  2016       1061134
11  2017        609054
12  2018         56991

### Department wise total salary with respective year

In [235]:
# Converted Hiringdate to date time 

Dept_Salary_by_year = HR_Df.groupby([HR_Df['year'].dt.year,'Department'])['Salary'].sum().reset_index()

#Renaming the column 
Dept_Salary_by_year.columns = ['year','Department','Total_Salary']

Dept_Salary_by_year.head(10)

   year         Department  Total_Salary
0  2006              Sales         64397
1  2007  Production               114177
2  2008      Admin Offices         63000
3  2008  Production               113504
4  2009      Admin Offices         99351
5  2009  Production               453079
6  2010              IT/IS        286157
7  2010  Production               391476
8  2010              Sales         60120
9  2011      Admin Offices         55000

 # Visualization

### Maritial Status(year wise)

In [236]:
Marital_Status = HR_Df.groupby([HR_Df['year'].dt.year, 'MaritalStatus']).size().reset_index(name = 'Employee_Count')

Marital_Status.columns = ['year','Marital_Status','Employee_Count']

Marital_Status.head(10)

   year Marital_Status  Employee_Count
0  2006      Separated               1
1  2007         Single               1
2  2007        Widowed               1
3  2008        Married               2
4  2008         Single               1
5  2009        Married               3
6  2009         Single               4
7  2010       Divorced               1
8  2010        Married               6
9  2010         Single               2

In [237]:
pip install dash plotly

Requirement already satisfied: dash in c:\users\charp\anaconda3\lib\site-packages (4.2.0)
Requirement already satisfied: plotly in c:\users\charp\anaconda3\lib\site-packages (6.3.0)
Requirement already satisfied: Flask<3.2,>=1.0.4 in c:\users\charp\anaconda3\lib\site-packages (from dash) (3.1.2)
Requirement already satisfied: Werkzeug<3.2 in c:\users\charp\anaconda3\lib\site-packages (from dash) (3.1.3)
Requirement already satisfied: importlib-metadata in c:\users\charp\anaconda3\lib\site-packages (from dash) (8.7.0)
Requirement already satisfied: typing_extensions>=4.1.1 in c:\users\charp\anaconda3\lib\site-packages (from dash) (4.15.0)
Requirement already satisfied: requests in c:\users\charp\anaconda3\lib\site-packages (from dash) (2.32.5)
Requirement already satisfied: retrying in c:\users\charp\anaconda3\lib\site-packages (from dash) (1.4.2)
Requirement already satisfied: nest-asyncio in c:\users\charp\anaconda3\lib\site-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in c:\users\charp\anaconda3\lib\site-packages (from dash) (80.9.0)
Requirement already satisfied: janus>=1.0.0 in c:\users\charp\anaconda3\lib\site-packages (from dash) (2.0.0)
Requirement already satisfied: blinker>=1.9.0 in c:\users\charp\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\charp\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (8.2.1)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\charp\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\charp\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\charp\anaconda3\lib\site-packages (from Flask<3.2,>=1.0.4->dash) (3.0.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\charp\anaconda3\lib\site-packages (from plotly) (2.7.0)
Requirement already satisfied: packaging in c:\users\charp\anaconda3\lib\site-packages (from plotly) (25.0)
Requirement already satisfied: colorama in c:\users\charp\anaconda3\lib\site-packages (from click>=8.1.3->Flask<3.2,>=1.0.4->dash) (0.4.6)
Requirement already satisfied: zipp>=3.20 in c:\users\charp\anaconda3\lib\site-packages (from importlib-metadata->dash) (3.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\charp\anaconda3\lib\site-packages (from requests->dash) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\charp\anaconda3\lib\site-packages (from requests->dash) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\charp\anaconda3\lib\site-packages (from requests->dash) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\charp\anaconda3\lib\site-packages (from requests->dash) (2026.1.4)
Note: you may need to restart the kernel to use updated packages.

In [238]:
HR_Df['Year'] = pd.to_datetime(HR_Df['HiringDate']).dt.year

app = Dash(__name__)

app.layout = html.Div([
    html.Label("Select Year"),
        dcc.Dropdown(
        id='year_dropdown',
        options=[
            {'label': y, 'value': y}
            for y in sorted(HR_Df['Year'].dropna().unique())
        ],
        value=HR_Df['Year'].min(),
        clearable=False
    ),

    dcc.Graph(id='marital_donut')

])

@app.callback(
    Output('marital_donut', 'figure'),
    Input('year_dropdown', 'value')
)

def update_chart(selected_year):

    filtered_df = HR_Df[HR_Df['Year'] == selected_year]

    marital_count = (
        filtered_df['MaritalStatus']
        .value_counts()
        .reset_index()
    )

    marital_count.columns = ['MaritalStatus', 'Count']

    fig = px.pie(
        marital_count,
        names='MaritalStatus',
        values='Count',
        hole=0.5,
        title=f' Year wise Marital Status - {selected_year}'
    )

    return fig

if __name__ == '__main__':
    app.run(debug=True)

### year wise Employee count by Department

In [239]:
Employee_Count_by_Department = HR_Df.groupby([HR_Df['year'].dt.year,'Department']).size().reset_index(name='Employee_by_Department')

Employee_Count_by_Department.columns =[ 'year','Department','Employee_by_Department']

Employee_Count_by_Department.head(10)

   year         Department  Employee_by_Department
0  2006              Sales                       1
1  2007  Production                              2
2  2008      Admin Offices                       1
3  2008  Production                              2
4  2009      Admin Offices                       1
5  2009  Production                              6
6  2010              IT/IS                       2
7  2010  Production                              6
8  2010              Sales                       1
9  2011      Admin Offices                       1

In [240]:
import ipywidgets as widgets
from IPython.display import display

def plot_department(year):

    filtered_df = HR_Df[HR_Df['year'].dt.year == year]

    Dept_Count = filtered_df.groupby('Department')['EmployeeID'].count()

    ax = Dept_Count.plot(kind='bar')
    ax.bar_label(ax.containers[0])
    plt.title(f'Employee Count by Department - {year}')
    plt.xlabel('Department')
    plt.ylabel('Employees')
    plt.xticks(rotation = 0)
    plt.show()

year_dropdown = widgets.Dropdown(
    options=sorted(HR_Df['year'].dt.year.unique()),
    description='Year'
    
)

widgets.interactive(plot_department, year=year_dropdown)

interactive(children=(Dropdown(description='Year', options=(np.int32(2006), np.int32(2007), np.int32(2008), np…

### Year wise Employee Performance

In [241]:
Employ_Performance_count = HR_Df.groupby([HR_Df['year'].dt.year,'PerformanceScore']).size().reset_index(name = "Employee_PF_count")

# Rename Column 
Employ_Performance_count.columns = ['year','PerformanceScore', 'Employee_PF_count']

Employ_Performance_count.head(10)

   year   PerformanceScore  Employee_PF_count
0  2006            Exceeds                  1
1  2007        Fully Meets                  2
2  2008        Fully Meets                  2
3  2008                PIP                  1
4  2009            Exceeds                  1
5  2009        Fully Meets                  6
6  2010            Exceeds                  1
7  2010        Fully Meets                  6
8  2010  Needs Improvement                  1
9  2010                PIP                  1

In [242]:
import ipywidgets as widgets
from IPython.display import display

def plot_PerformanceScore(year):

    filtered_df = HR_Df[HR_Df['year'].dt.year == year]

    Performance_Count = filtered_df['PerformanceScore'].value_counts()

    plt.figure(figsize=(8,6))
    plt.pie(
        Performance_Count,
        labels=Performance_Count.index,
        autopct='%1.1f%%'
    )
    plt.title(f'Year Wise Employee Performance - {year}')
    plt.show()

year_dropdown = widgets.Dropdown(
    options=sorted(HR_Df['year'].dt.year.dropna().unique()),
    description='Year:'
)

interactive_plot = widgets.interactive(
    plot_PerformanceScore,
    year=year_dropdown
)

display(interactive_plot)

interactive(children=(Dropdown(description='Year:', options=(np.int32(2006), np.int32(2007), np.int32(2008), n…

### Year wise Recruitment Source

In [243]:
Recruitment_Source = HR_Df.groupby([HR_Df['year'].dt.year,'RecruitmentSource']).size().reset_index(name = 'Employee_Count')

# Renaming the Column
Recruitment_Source.columns = ['year','RecruitmentSource','Employee_Count']

Recruitment_Source.head(10)

   year   RecruitmentSource  Employee_Count
0  2006              Indeed               1
1  2007       Google Search               1
2  2007               Other               1
3  2008  Diversity Job Fair               1
4  2008       Google Search               1
5  2008              Indeed               1
6  2009       CareerBuilder               1
7  2009  Diversity Job Fair               2
8  2009       Google Search               1
9  2009              Indeed               2

In [244]:
import ipywidgets as widgets
from IPython.display import display

def plot_RecruitmentSource(year):

    filtered_df = HR_Df[HR_Df['year'].dt.year == year]

    RecruitmentSource_Count = filtered_df.groupby('RecruitmentSource')['EmployeeID'].count()

    ax = RecruitmentSource_Count.plot(kind='barh',figsize=(8,6))
    ax.bar_label(ax.containers[0])
    plt.title(f'Recruitment Source - {year}')
    plt.xlabel('employees')
    plt.ylabel('RecruitmentSource')
    plt.xticks(rotation = 0)
    plt.show()

year_dropdown = widgets.Dropdown(
    options=sorted(HR_Df['year'].dt.year.unique()),
    description='Year'
    
)

widgets.interactive(plot_RecruitmentSource, year=year_dropdown)

interactive(children=(Dropdown(description='Year', options=(np.int32(2006), np.int32(2007), np.int32(2008), np…

### Employee Satisfaction (year by year)

In [245]:
# Create new column  for employee satiscfaction category
HR_Df['Emp_Satisfaction_Category'] = HR_Df['EmployeeSatisfaction'].replace({
    5:"very High",
    4: "High",
    3: "Acceptable",
    2: "Low",
    1: "Very Low"
})

In [246]:
HR_Df['Emp_Satisfaction_Category']

0       very High
1      Acceptable
2      Acceptable
3       very High
4            High
          ...
306          High
307           Low
308     very High
309    Acceptable
310     very High
Name: Emp_Satisfaction_Category, Length: 311, dtype: object

In [249]:
Emp_Satisfaction_Score = HR_Df.groupby([HR_Df['year'].dt.year,'Emp_Satisfaction_Category']).size().reset_index(name ="Satisfaction_score")

# rename new column

Emp_Satisfaction_Score.columns = ['year','Emp_Satisfaction_Category', 'Satisfaction_score']

Emp_Satisfaction_Score.head(10)

   year Emp_Satisfaction_Category  Satisfaction_score
0  2006                Acceptable                   1
1  2007                Acceptable                   1
2  2007                      High                   1
3  2008                       Low                   2
4  2008                 very High                   1
5  2009                Acceptable                   2
6  2009                      High                   2
7  2009                 very High                   3
8  2010                Acceptable                   3
9  2010                      High                   3

In [253]:
import ipywidgets as widgets
from IPython.display import display

def plot_SatisfactionScore(year):

    filtered_df = HR_Df[HR_Df['year'].dt.year == year]

    EMP_Satisfaction_Count = filtered_df['Emp_Satisfaction_Category'].value_counts()

    plt.figure(figsize=(8,6))
    plt.pie(
        EMP_Satisfaction_Count,
        labels=EMP_Satisfaction_Count.index,
        autopct='%1.1f%%'
    )
    plt.title(f'Year Wise Employee Satisfaction Score - {year}')
    plt.show()

year_dropdown = widgets.Dropdown(
    options=sorted(HR_Df['year'].dt.year.dropna().unique()),
    description='Year:'
)

interactive_plot = widgets.interactive(
    plot_SatisfactionScore,
    year=year_dropdown
)

display(interactive_plot)

interactive(children=(Dropdown(description='Year:', options=(np.int32(2006), np.int32(2007), np.int32(2008), n…

### State wise Department Count

In [257]:
State_vs_DeptCount = HR_Df.groupby([HR_Df['year'].dt.year,'State']).size().reset_index(name ='Dept_count')

# Rename Column
State_vs_DeptCount.columns = ['year','State','Dept_count']

State_vs_DeptCount.head(10)

   year State  Dept_count
0  2006    ND           1
1  2007    MA           2
2  2008    MA           3
3  2009    MA           7
4  2010    CT           1
5  2010    MA           7
6  2010    MT           1
7  2011    AZ           1
8  2011    CA           1
9  2011    CT           2

In [272]:
import plotly.express as px

import ipywidgets as widgets
from IPython.display import display

def plot_map(year):
    data = HR_Df[HR_Df['year'].dt.year == year]

    fig = px.choropleth(
        data,
        locations='State',
        locationmode='USA-states',
        color='Department',
        color_continuous_scale='Blues',
        title=f"State-wise Employee Count - {year}"
    )
        # increase map size
    fig.update_layout(
        width=1000,
        height=700
    )


    fig.show()

    

year_dropdown = widgets.Dropdown(
    options=sorted(HR_Df['Year'].dropna().unique()),
    description='Year:'
)

widgets.interactive(plot_map, year=year_dropdown)

interactive(children=(Dropdown(description='Year:', options=(np.int32(2006), np.int32(2007), np.int32(2008), n…